name: tekartik_mdl_js
version: 0.5.0
description: Material design lite base resources and wrappers

homepage: https://github.com/tekartik/mdl_js.dart
publish_to: none
environment:
  sdk: '>=3.4.0-0 <4.0.0'
dependencies:
  js: any
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart3a
    version: '>=0.6.8+1'
  pub_semver:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
dev_dependencies:
  test: any
  dev_build: '>=1.0.0'
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'
  process_run: '>=0.10.1'
